### ISSUE TITLE
USER STORY: Navigation

### ISSUE THREAD

**Issue by TulaUnogi** [TulaUnogi/bat-choice-clothing#19]
As a **User** I can **find the navigation links**, so I can **easily navigate across the website.**

### Acceptance criteria

- Sticky navbar on every page
- Working and appropriately named links
- Additional links where useful/ necessary (e.g. "Proceed to checkout", "Back to My Profile"...)

### Tasks

- [x] Add and style sticky navbar in base.html template 
- [x] Name links appropriately to their content/ role and ensure they lead to assigned pages
- [x] Include additional links where they may be useful or necessary
- [x] Add footer with social links
