### ISSUE TITLE
USER STORY: User Profile

### ISSUE THREAD

**Issue by TulaUnogi** [TulaUnogi/bat-choice-clothing#20]
As a **User ** I can **create and manage My Profile**, so I can **keep my account information up to date and securely stored** for me to review at any time.

### Acceptance criteria

- User can create a profile
- User can update and delete their profile 
- User can access their order history through the profile page

### Tasks

- [x] Set up django-allauth 
- [x] Add and style django-allauth templates
- [x] Create and style My Profile templates
- [x] Display order history in My Profile 
- [x] Add Order Details button to Order History
- [x] Add a function and button allowing to update User information
- [x] Add a function and button allowing to delete User profile

**Comment by TulaUnogi** [comment]
Decided to change the button for link instead in order history
