### ISSUE TITLE
USER STORY: Products display

### ISSUE THREAD

**Issue by TulaUnogi** [TulaUnogi/bat-choice-clothing#21]
As a **User** I can **easily find pictures of the products**, so I can **buy items that interest me.**

### Acceptance criteria

- Product images are clearly displayed for Users to browse through
- User can access product details by clicking on the product image
- Products contain appropriate description that includes all the necessary data, like e.g. price, colour and size
- Product page includes buttons: "Add to basket" and "Back to shop"

### Tasks

- [x] Add view for base products page
- [x] Add base products url path
- [x] Create base products page template
- [x] Add view for detailed product page
- [x] Add product details url path
- [x] Create template for product details page including buttons mentioned above
