### ISSUE TITLE
USER STORY: Product filtering and searching

### ISSUE THREAD

**Issue by TulaUnogi** [TulaUnogi/bat-choice-clothing#22]
As a **User** I can **filter and search products**, so I can **easier find items I would like to buy.**

### Acceptance criteria

- User can filter the items by categories
- User can sort the items by price
- User can sort the items by names
- User can use the search box to filter through item names and descriptions

### Tasks

- [x] Set up urls
- [x] Write a method using Q to handle queries 
- [x] Add functional dropdown menu for sorting
- [x] Add functional search bar

**Comment by TulaUnogi** [comment]
Edit: moving additional sorting options by colour and size to NINTH for the future improvement
