### ISSUE TITLE
USER STORY: Shopping Basket

### ISSUE THREAD

**Issue by TulaUnogi** [TulaUnogi/bat-choice-clothing#23]
As a **User** I can **add items to basket**, so I can **purchase them**

### Acceptance criteria

- Front-end shopping basket button and template
- After clicking "Add to basket" an item is being added to basket and success message is being displayed
- User can access the content of their basket to review and edit their order
- User can see the separate prices for the items and grand total
- User can remove the item from the basket
- User can proceed to checkout 

### Tasks

- [x] Write add to basket and remove from basket views
- [x] Design templates
- [x] Assign urls and actions to links
- [x] Write method to calculate delivery costs and free delivery treshold
