### ISSUE TITLE
USER STORY: Checkout

### ISSUE THREAD

**Issue by TulaUnogi** [TulaUnogi/bat-choice-clothing#24]
As a **User** I can **use my card online*, so I can **pay for my order without leaving my house**

### Acceptance criteria

- User can enter the card details using frontend form
- Card details are checked for validation
- Card payment process is secure
- User gets a feedback on their payment being successful/ unsuccessful 
- After successful transaction User gets redirected to their order page

### Tasks

- [x] Set up and link Stripe to shop's website
- [x] Import Stripe HTML form
- [x] Set up webhooks and messages
- [x] Test if payments work properly
