### ISSUE TITLE
USER STORY: Contact form

### ISSUE THREAD

**Issue by TulaUnogi** [TulaUnogi/bat-choice-clothing#26]
As a **User** I can **contact the admin**, so I can **ask questions or report issues**

### Acceptance criteria

- Contact link is available across the website through menu
- Contact page includes frontend contact form
- There's appropriate backend in place to handle email sending
- After sending an email a success message is being displayed

### Tasks

- [x] Set up link and url
- [x] Add template including a frontend form
- [x] Connect to EmailJS
- [x] Set up JavaScript to add sending emails functionality

**Comment by TulaUnogi** [comment]
Decided to use EmailJS to handle emails.
