### ISSUE TITLE
USER STORY: Newsletter

### ISSUE THREAD

**Issue by TulaUnogi** [TulaUnogi/bat-choice-clothing#27]
As a **User** I can **sign up to newsletter**, so I can **receive company's updates and promo codes on my email**

### Acceptance criteria

- Sign up to newsletter link present on a landing page
- Admin can send newsletters to all the User emails in newsletter database

### Tasks

- [x] Set up Mailchimp
- [x] Add embedded link to home page
- [x] Style a Mailchimp sign up pop-up
