### ISSUE TITLE
USER STORY: Custom error pages

### ISSUE THREAD

**Issue by TulaUnogi** [TulaUnogi/bat-choice-clothing#28]
As a **User** I can **see custom User friendly error pages**, so I can **understand what kind of error I have encountered** and so I can **return to the home page.**

### Acceptance criteria

- User can see a custom error page, that is stylistically consistent with the rest of the site
- User can se a number of an error
- Error messages are written in a User- friendly way
- User can return to homepage by clicking return button

### Tasks

- [x] Create custom error handlers
- [x] Create custom templates that display errors and return button
- [x] Set up urls
