### ISSUE TITLE
USER STORY: Filtering by colour and size

### ISSUE THREAD

**Issue by TulaUnogi** [TulaUnogi/bat-choice-clothing#30]
As a ** User ** I can ** filter the items by colour and size **, so I can ** find the items that interest me faster **

### Acceptance criteria

- User can filter the items by colour
- User can filter the items by size

### Tasks

- [ ] Add the 'filter' dropdown to products special navbar
- [ ] Design a colour picker
- [ ] Write views for filtering by product and size
