### ISSUE TITLE
USER STORY: SEO

### ISSUE THREAD

**Issue by TulaUnogi** [TulaUnogi/bat-choice-clothing#37]
As a **Store Owner** I can **see my website presenting good SEO practice**, so it can **be easily searchable for my customers**

### Acceptance criteria

- robots.txt present in repository
- sitemap.xml present in repository
- appropriate metadata present in html

### Tasks

- [x] Add meta tags 
- [ ] Add robots.txt
- [ ] Generate and add sitemap.xml
