### ISSUE TITLE
README: Update Agile Development module

### ISSUE THREAD

**Issue by TulaUnogi** [TulaUnogi/bat-choice-clothing#9]
### Write the up-to-date content for the Agile Development module.

- [ ] Write an overview
- [ ] Describe the User Stories
- [ ] Add links to Kanban and Stories
